## Database Schema (SQL) ##
CREATE TABLE Author (
  AuthorID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  DateOfBirth DATE,
  Nationality VARCHAR(100)
);

CREATE TABLE Publisher (
  PublisherID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  Address VARCHAR(30),
  ContactInformation VARCHAR(255)
);

CREATE TABLE Book1 (
  BookID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ISBN VARCHAR(20) UNIQUE NOT NULL,
  Title VARCHAR(255) NOT NULL,
  PublisherID INT,
  PublicationDate DATE,
  Genre VARCHAR(100),
  Price DECIMAL(10, 2),
  StockQuantity INT,
  FOREIGN KEY (PublisherID) REFERENCES Publisher(PublisherID)
);

CREATE TABLE Customer (
  CustomerID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  Email VARCHAR(255) UNIQUE NOT NULL,
  PhoneNumber VARCHAR(20),
  Address VARCHAR(10)
);

CREATE TABLE Order2 (
  OrderID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CustomerID INT,
  OrderDate DATE NOT NULL,
  TotalAmount DECIMAL(10, 2) NOT NULL,
  OrderStatus VARCHAR(40),
  FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
);
